### ISSUE TITLE
Meta2 restart

### ISSUE THREAD

**Issue by GuillaumeDelaporte** [open-io/oio-sds#375] opened 2016-01-20 17:10 UTC
I had an unexpected meta2 restart in my environment.

Before it, I had a lot of this following lines in my logs : 
```
2016-01-20T13:11:09.283406+00:00 bench-node1 OIO,OPENIO,meta2,0: warning  6925 D763 log WRN oio.sqlite [defer_GETVERS] Election initiated (PRELOST) but get_peers error: (431) get_peers(CE6C7CD99E1820FE9E61D4B3107B1ACA25DDE232E295E2112A4492FCBE63A01E.1,meta2): Base not man
aged
2016-01-20T13:11:09.285824+00:00 bench-node1 OIO,OPENIO,meta2,0: warning  6925 D763 log WRN oio.sqlite [defer_GETVERS] Election initiated (PRELEAD) but get_peers error: (431) get_peers(720533EADBBE38DB1B93CFB8EB1F4858F5E8972E616B37CFB8764E3EC41E2DFF.1,meta2): Base not man
aged
```

Terminated by this two lines : 
```
2016-01-20T13:11:21.097689+00:00 bench-node1 OIO,OPENIO,meta2,0: err  6925 D36F log ERR oio.sqlite BUG: Trying to close [B749732D6E79F040FD24D359902C0A185D1E0E3C8828CEA81235A2BB77DE7535.1][meta2] with dirty admin
2016-01-20T13:11:27.183601+00:00 bench-node1 OIO,OPENIO,meta2,0: err  24064 994F log ERR oio.sqlite BUG: Trying to close [33532D284769FF6E257C91C133813FDE5E50EDE6D34D0B88445259728AB75F0D.1][meta2] with dirty admin
```

Then the meta2 had restarted, and the situation came back to a normal state.

Seems to have a relation with this pull request : https://github.com/open-io/oio-sds/pull/367

**Comment by jfsmig** [comment] 2016-01-28 18:07
The cause of the "dirty admin" symptom has been fixed in #385

**Closed by jfsmig** 2016-01-28 18:07 UTC
