### ISSUE TITLE
Ubuntu server 15.04 : oio-account-server crashes when launched by gridinit

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#109] opened 2015-07-29 13:43 UTC
The oio-account-server process ends with segfault loop when launched by gridinit (e.g. during the oio-reset procedure) while it perfectly works when manually started.

That could have something to do with the issue #102 

Not sure it could serve, but here is the trace :
>Core was generated by `/usr/bin/python /usr/local/bin/oio-account-server /home/openio/.oio/sds/conf/NS'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000492b6a in ?? ()
(gdb) bt
0  0x0000000000492b6a in ?? ()
1  0x00000000004cdcce in PyEval_EvalFrameEx ()
2  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
3  0x00000000004cb6b1 in PyEval_EvalCodeEx ()
4  0x00000000004ce7d3 in PyEval_EvalFrameEx ()
5  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
6  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
7  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
8  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
9  0x00000000004cd4e2 in PyEval_EvalFrameEx ()
10 0x00000000004cd4e2 in PyEval_EvalFrameEx ()
11 0x00000000004cb6b1 in PyEval_EvalCodeEx ()
12 0x00000000004caf56 in PyEval_EvalCode ()
13 0x00000000004d134e in PyEval_EvalFrameEx ()
14 0x00000000004cb6b1 in PyEval_EvalCodeEx ()
15 0x000000000050481f in ?? ()
16 0x00000000004fc182 in PyRun_FileExFlags ()
17 0x00000000004fb247 in PyRun_SimpleFileExFlags ()
18 0x000000000049aa6e in Py_Main ()
19 0x00007f25da1b6a40 in __libc_start_main (main=0x49a500 <main>, argc=3, 
    argv=0x7fff67bbc1a8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fff67bbc198) at libc-start.c:289
20 0x000000000049a429 in _start ()

**Comment by jfsmig** [comment] 2015-08-11 14:24
We were unable to reproduce this. I do not close the issue immediately, waiting for a new case.

**Comment by jfsmig** [comment] 2015-08-20 15:23
Ok, no-one reproduced within the past 9 days.
We are done.

**Closed by jfsmig** 2015-08-20 15:23 UTC
Labels: wontfix
