### ISSUE TITLE
Ubuntu server 15.04 : oio-reset lasts until one minute

### ISSUE THREAD

**Issue by Reaskel** [open-io/oio-sds#102] opened 2015-07-13 15:38 UTC
The oio-reset procedure on an Ubuntu server system often lasts until one minute instead of the around ten seconds expected.
Two times on 3, the procedure starts repeating dozens of times the following instructions :

> pkill --full -0 gridinit
pkill --full gridinit
sleep 2

It seems that some gridinit process resists the kill procedure.
When using a ps command to find those running during the loop, I always find these ones :

> oio-svc-monitor -s OIO,NS,account,1 -p 1 -m oio-account-monitor.py -i NS|account|192.168.56.102:6005 -c oio-account-server /home/openio/.oio/sds/conf/NS-account-server.conf

> /usr/bin/python /home/openio/build/bin/oio-account-monitor.py NS|account|192.168.56.102:6005

Is it possible to improve the oio-reset procedure to solve that delay problem ?

**Comment by jfsmig** [comment] 2015-09-23 13:10
The oio-reset.sh execution time has been reduced in commit 81c1f2914926231c4aea9668a81c2a407b12f8e1. I hope the cleanup branch will be merged soon.

**Comment by jfsmig** [comment] 2015-12-29 15:24
Could not reproduce, it works on my personnal Ubuntu 15.10 and my 14.04 VM.

**Closed by jfsmig** 2015-12-29 15:24 UTC
Labels: enhancement
